### ISSUE TITLE
broken link for Clojure aware editors on the install page

### ISSUE THREAD

**Issue by shishini** [practicalli/clojure#462]
The second link to [Clojure aware editors](https://practical.li/clojure-editors/)
on the [Install](https://practical.li/clojure/install/) page 
Point to https://practical.li/clojure-editors
Instead of [Clojure aware editor](https://practical.li/clojure/clojure-editors/)  https://practical.li/clojure/clojure-editors/

**Comment by practicalli-john** [comment]
Thank you for letting me know.  I have fixed the link and published a new version of the book
